# -*- coding: utf-8 -*-
"""모범음식점 데이터 전처리.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rfn7Ncyk94UppGCksMJ3_2BOKaXNcwwV
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import re

# 0. 엑셀 파일 로드
df_raw = pd.read_excel("/content/모범음식점_리스트_지오코딩_4326.xlsx")

# 1. 필요한 컬럼만 선택
need_cols = ["restaurant_name","address","category","menu","phone_number","lon","lat","ctp_kor_nm","sig_kor_nm","emd_kor_nm"]
df = df_raw[need_cols].copy()

# 2. 업소명+주소(도로명주소+소재지주소) 기준 중복 제거
def norm_key(x):
    t = str(x).strip().lower()
    t = re.sub(r"\s+", " ", t)
    t = re.sub(r"[^\w\s가-힣]", "", t)
    return t

df["name_key"] = df["restaurant_name"].map(norm_key)
df["addr_key"] = df["address"].fillna("").map(norm_key)
df = df.drop_duplicates(subset=["name_key","addr_key"]).reset_index(drop=True)

# 3. 결측치 처리
# 음식의유형이 없으면 주된음식종류로 보완
df["category"] = np.where(
    df["category"].isna() | (df["category"].str.strip()==""),
    df["menu"],
    df["category"]
)
# 전화번호 빈칸 처리
df["phone_number"] = df["phone_number"].replace({"": np.nan})

# 4. 소재지주소에서 시/구 분리
def split_address(addr):
    tokens = str(addr).split()
    si, gu = None, None
    if len(tokens) > 0: si = tokens[0]
    if len(tokens) > 1: gu = tokens[1]
    return pd.Series([si, gu])

df[["ctp_kor_nm","sig_kor_nm"]] = df["address"].apply(split_address)

# 5. 전화번호 표준화
# ---------------------------
# 지역번호 매핑 테이블
area_code_map = {
    "서울특별시": "02",
    "부산광역시": "051",
    "대구광역시": "053",
    "인천광역시": "032",
    "광주광역시": "062",
    "대전광역시": "042",
    "울산광역시": "052",
    "세종특별자치시": "044",
    "경기도": "031",
    "강원특별자치도": "033",
    "충청북도": "043",
    "충청남도": "041",
    "전북특별자치도": "063",
    "전라남도": "061",
    "경상북도": "054",
    "경상남도": "055",
    "제주특별자치도": "064",
}

def normalize_phone_with_area(phone, si):
    if pd.isna(phone) or not str(phone).strip():
        return np.nan
    digits = re.sub(r"\D", "", str(phone))

    # 1) 서울(02)
    if digits.startswith("02"):
        if len(digits) == 9:
            return f"02-{digits[2:5]}-{digits[5:]}"
        elif len(digits) == 10:
            return f"02-{digits[2:6]}-{digits[6:]}"

    # 2) 타지역 (0XX)
    if digits.startswith("0") and len(digits) == 10:
        return f"{digits[:3]}-{digits[3:6]}-{digits[6:]}"
    if digits.startswith("0") and len(digits) == 11:
        return f"{digits[:3]}-{digits[3:7]}-{digits[7:]}"

    # 3) 지역번호 누락
    area_code = area_code_map.get(si, "")
    if area_code:
        if area_code == "02":
            if len(digits) == 7:
                return f"02-{digits[:3]}-{digits[3:]}"
            elif len(digits) == 8:
                return f"02-{digits[:4]}-{digits[4:]}"
        else:
            if len(digits) == 7:
                return f"{area_code}-{digits[:3]}-{digits[3:]}"
            elif len(digits) == 8:
                return f"{area_code}-{digits[:4]}-{digits[4:]}"
    return digits

df["phone_number"] = df.apply(lambda r: normalize_phone_with_area(r["phone_number"], r["ctp_kor_nm"]), axis=1)

# 6. 최종 CSV 저장
df_final = df[[
    "restaurant_name","address","category","menu","phone_number",
    "lon","lat","ctp_kor_nm","sig_kor_nm","emd_kor_nm"
]]
df_final.to_csv("restaurant_clean.csv", index=False, encoding="utf-8")

print("전처리 완료 → restaurant_clean.csv 저장됨")